root: true

parser: babel-eslint

settings:
  import/resolver: webpack

parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    jsx: true
    destructuring: true
    spread: true

env:
  browser: true

plugins:
  - react

extends: airbnb

rules:
  no-console: off
  no-alert: off
  no-unused-vars: warn
  semi: [warn, never]
  new-cap: off
  quotes: [warn, single]
  react/prop-types: off
  react/prefer-stateless-function: off
  no-else-return: off
  no-use-before-define: off
  no-param-reassign: off
  jsx-a11y/href-no-hash: off
  one-var: off

