root: true

parser: babel-eslint


parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    jsx: true
    destructuring: true
    spread: true

globals:
  PORT: true
  PRODUCTION: true

env:
  browser: true

plugins:
  - react

extends: airbnb

rules:
  no-console: off
  no-alert: off
  no-unused-vars: warn
  semi: [warn, never]
  new-cap: off
  quotes: [warn, single]
  react/prop-types: off
  react/prefer-stateless-function: off
  no-else-return: off
  no-use-before-define: off
  no-param-reassign: off
  jsx-a11y/href-no-hash: off
  jsx-a11y/no-static-element-interactions: off
  react/no-array-index-key: off
  react/forbid-prop-types: off
  one-var: off
  linebreak-style: off
  jsx-a11y/click-events-have-key-events: off

