Brand:
 - knowledge
 - hot
 - trend
 - related
Person:
 - detail
 - empty
 - empty
 - empty
Company:
 - empty
 - empty
 - empty
 - empty
tabMap:
 Brand:
  knowledge: 品牌知识
  hot: 热点聚焦
  trend: 品牌动态
  related: 相关品牌
 Person:
  detail: 人物简介
  empty: 暂无
 Company:
  empty: 暂无
nameMap:
  Brand: 品牌
  Company: 公司
  Person: 人物
  brand: 品牌
  name: 名称
  sku: sku编号
  source: 来源
  url: 链接
  description: 介绍
