Brand:
 - key: knowledge
   name: 品牌知识
 - key: hot
   name: 热点聚焦
 - key: trend
   name: 品牌动态
 - key: relatedBrands
   name: 相关品牌
Person:
 - key: detail
   name: 人物简介
 - key: story
   name: 人物故事
 - key: empty
   name: 暂无
 - key: empty
   name: 暂无
Company:
 - key: empty
   name: 暂无
 - key: empty
   name: 暂无
 - key: empty
   name: 暂无
 - key: empty
   name: 暂无
Product:
 - key: detail
   name: 商品信息
 - key: model
   name: 商品规格
nameMap:
  Brand: 品牌
  Company: 公司
  Person: 人物
  brand: 品牌
  name: 名称
  sku: sku编号
  source: 来源
  url: 链接
  description: 介绍
