Brand:
 - key: knowledge
   name: 品牌知识
#  - key: hot
  #  name: 热点聚焦
#  - key: trend
  #  name: 品牌动态
 - key: relatedBrands
   name: 相关品牌
Person:
 - key: detail
   name: 人物简介
 - key: story
   name: 人物故事
Company:
 - key: detail
   name: 企业信息
 - key: story
   name: 企业故事
 - key: relatedBrands
   name: 相关品牌
Product:
 - key: detail
   name: 商品信息
 - key: spec
   name: 商品规格
 - key: priceSales
   name: 价格销量
nameMap:
  Brand: 品牌
  Company: 公司
  Person: 人物
  Product: 产品
  brand: 品牌
  name: 名称
  sku: 商品编号
  source: 来源
  url: 链接
  description: 介绍
